### ISSUE TITLE
Some suggestions to enrich the experience

### ISSUE THREAD

**Issue by texcalac** [samuelmeuli/mini-diary#17]
* Markdown support
* Several notes per day
* Choose folder to store my database. With this I can share my diary with other computer.
* tags

Congratulations, great work!

**Comment by samuelmeuli** [comment]
Hi @texcalac,

Thanks for your feedback!

* Since v2, diary entries are stored in the Markdown format. You can import from and export to `.md` files from the menu. I decided to only support a subset of the Markdown features (bold, italics, bulleted and numbered lists) because this app shouldn't be a full-blown text editor, but rather provide a simple way to write your diary. Are there any specific Markdown features you are missing?
* The same goes for tags and the ability to have multiple entries per day. Its simplicity and intuitive design are what make Mini Diary different from other apps. I'm afraid adding too many features (like tags) would move it away from that philosophy. There are many other great diary apps if you need a tool with more advanced features.
* You can already change the folder where your diary file is stored: Unlock your diary and change the setting under File → Preferences. That way, you can e.g. store your file in Google Drive or Dropbox to keep it synced between devices. (Please note that this does not work with the Mac App Store version due to sandboxing. If you need the feature on a Mac, you can download the DMG of the non-sandboxed version from the [releases page](https://github.com/samuelmeuli/mini-diary/releases/latest).)
