### ISSUE TITLE
Ask for password before resetting diary

### ISSUE THREAD

**Issue by yeboahnanaosei** [samuelmeuli/mini-diary#32]
Hi Samuel, thanks for such a nice application.

I was thinking that as a security measure, you have to ask for the password before resetting the diary.

**Comment by samuelmeuli** [comment]
Hey @yeboahnanaosei,

The reason I added this button is because I've received multiple emails from users who forgot their password and wanted to create a new diary with a new password.

And even when asking for a password, users could still just delete the diary file manually, so it wouldn't offer any real protection.
