### ISSUE TITLE
Cloud sync

### ISSUE THREAD

**Issue by alminisl** [samuelmeuli/mini-diary#46]
Hello,

Love the app, currently I'm hacking together a prototype with cloud sync. My question is did you ever plan on making it work with cloud sync ? 

As for my motivation, I love the app use it everyday but I can not use it on different devices. So I'm trying to create now a way to make the cloud sync work so I can sync it between my 2 Pcs for now. 

Please let me know what you think of this and if this is something you intended. 

Thanks

**Comment by samuelmeuli** [comment]
Hi @alminisl,

Thanks for opening the issue!

I'd rather not build cloud sync functionality into the app, in order to keep it simple and offline-only. You can still get sync to work though by storing the diary file e.g. in your Dropbox folder. There's a short guide on the website (https://minidiary.app) on how you can do this 🙂

**Comment by alminisl** [comment]
> Hi @alminisl,
> 
> Thanks for opening the issue!
> 
> I'd rather not build cloud sync functionality into the app, in order to keep it simple and offline-only. You can still get sync to work though by storing the diary file e.g. in your Dropbox folder. There's a short guide on the website ([minidiary.app](https://minidiary.app)) on how you can do this 🙂

aah thanks did not know about that, totally understand! Thanks!
